/*
 |c/f2p *.c
 */

extern u64int	addrofref(u64int refaddr, int idx);
extern void	changed(Memblk *b);
extern void	clean(Memblk *b);
extern Memblk*	dballoc(Fsys *fs, uint type);
extern void	dbclear(Fsys *fs, u64int addr, int type);
extern u64int	dbdecref(Fsys *fs, u64int addr);
extern Memblk*	dbdup(Fsys *fs, Memblk *b);
extern Memblk*	dbget(Fsys *fs, uint type, u64int addr);
extern u64int	dbgetref(Fsys *fs, u64int addr);
extern void	dbincref(Fsys *fs, u64int addr);
extern long	dbread(Fsys *fs, Memblk *b);
extern void	dbsetref(Fsys *fs, u64int addr, u64int ref);
extern long	dbwrite(Fsys *fs, Memblk *b);
extern void	delchild(Memblk *d, Child *c);
extern Memblk*	dfcreate(Fsys *fs, Memblk *parent, char *name, char *uid, ulong mode);
extern void	dffreeze(Fsys *fs, Memblk *f);
extern void	dflink(Fsys *fs, Memblk *d, Memblk *f);
extern void	dfloaddir(Fsys *fs, Memblk *d, int locked);
extern Memblk*	dfmelt(Fsys *fs, Memblk *f);
extern ulong	dfpread(Fsys *fs, Memblk *f, void *a, ulong count, uvlong off);
extern ulong	dfpwrite(Fsys *fs, Memblk *f, void *a, ulong count, uvlong off);
extern long	dfrattr(Fsys *fs, Memblk *f, char *name, void *val, long count);
extern Blksl	dfreadblk(Fsys *fs, Memblk *f, ulong len, uvlong off);
extern int	dfreclaim(Fsys *fs, Memblk *f);
extern Blksl	dfslice(Fsys *fs, Memblk *f, ulong len, uvlong off, int iswr);
extern void	dfsync(Fsys *fs, Memblk *f);
extern void	dfunlink(Fsys *fs, Memblk *d, Memblk *f);
extern Memblk*	dfwalk(Fsys *fs, Memblk *d, char *name, int iswr);
extern long	dfwattr(Fsys *fs, Memblk *f, char *name, void *val, long nval);
extern Blksl	dfwriteblk(Fsys *fs, Memblk *f, uvlong off);
extern void	disktohost(Memblk *b);
extern ulong	embedattrsz(Memblk *f);
extern void	fsdump(Fsys *fs);
extern Fsys*	fsfmt(char *dev);
extern Memblk*	fsfreeze(Fsys *fs);
extern Fsys*	fsopen(char *dev);
extern void	fsreclaim(Fsys *fs);
extern void	fssync(Fsys *fs);
extern void	gmeta(Fmeta *meta, void *buf, ulong nbuf);
extern Memblk*	hosttodisk(Memblk *b);
extern void	isdir(Memblk *d);
extern int	iserror(char *s);
extern void	isfile(Memblk *d);
extern void	isloaded(Memblk *d);
extern void	ismelted(Memblk *b);
extern void	isnotdir(Memblk *d);
extern void	isrlocked(Memblk *b);
extern void	iswlocked(Memblk *b);
extern void	main(int argc, char *argv[]);
extern void	main(int argc, char *argv[]);
extern void	main(int, char *argv[]);
extern Memblk*	mballoc(Fsys *fs, u64int addr);
extern Memblk*	mbdup(Fsys *fs, Memblk *b);
extern int	mbfmt(Fmt *fmt);
extern Memblk*	mbget(Fsys *fs, u64int addr);
extern Memblk*	mbhash(Fsys *fs, Memblk *b);
extern void	mbput(Fsys *fs, Memblk *b);
extern void	mbunhash(Fsys *fs, Memblk *b);
extern void	meltedref(Fsys *fs, Memblk *rb);
extern u64int	newblkaddr(Fsys *fs);
extern uvlong	now(void);
extern void	okaddr(Fsys *fs, u64int addr);
extern ulong	pmeta(void *buf, ulong nbuf, Fmeta *meta);
extern u64int	refaddr(u64int addr, int *idx);
extern Memblk*	walkpath(Fsys *fs, Memblk *f, char *elems[], int nelems);
