extern u64int	addrofref(u64int refaddr, int idx);
extern void	changed(Memblk *b);
extern void	checktag(u64int tag, uint type, u64int addr);
extern void	clean(Memblk *b);
extern void	consprint(char *fmt, ...);
extern long	consread(char *buf, long count);
extern long	conswrite(char *buf, long count);
extern Memblk*	dballoc(uint type);
extern void	dbclear(u64int addr, int type);
extern u64int	dbdecref(u64int addr);
extern Memblk*	dbdup(Memblk *b);
extern int	dbgclr(uchar flag);
extern Memblk*	dbget(uint type, u64int addr);
extern u64int	dbgetref(u64int addr);
extern u64int	dbincref(u64int addr);
extern long	dbread(Memblk *b);
extern void	dbsetref(u64int addr, int ref);
extern long	dbwrite(Memblk *b);
extern void	dfaccessok(Memblk *f, char *uid, int bits);
extern ulong	dfbno(Memblk *f, uvlong off, ulong *boffp);
extern u64int	dfchdentry(Memblk *d, u64int addr, u64int naddr, int iswr);
extern Memblk*	dfchild(Memblk *f, int n);
extern Memblk*	dfcreate(Memblk *parent, char *name, char *uid, ulong mode);
extern void	dfdropblks(Memblk *f, ulong bno, ulong bend);
extern int	dfdump(Memblk *f, int disktoo);
extern int	dffreeze(Memblk *f);
extern void	dflink(Memblk *d, Memblk *f);
extern void	dflist(Memblk *f, char *ppath);
extern int	dfmap(Memblk *f, Blkf pre, Blkf post, Blkf bf, int isdisk, int lk);
extern Memblk*	dfmelt(Memblk *f);
extern ulong	dfpread(Memblk *f, void *a, ulong count, uvlong off);
extern ulong	dfpwrite(Memblk *f, void *a, ulong count, uvlong off);
extern long	dfrattr(Memblk *f, char *name, void *val, long count);
extern int	dfreclaim(Memblk *f);
extern void	dfremove(Memblk *p, Memblk *f);
extern Blksl	dfslice(Memblk *f, ulong len, uvlong off, int iswr);
extern int	dfsync(Memblk *f);
extern void	dfunlink(Memblk *d, Memblk *f);
extern Memblk*	dfwalk(Memblk *d, char *name, int iswr);
extern long	dfwattr(Memblk *f, char *name, void *val, long nval);
extern void	disktohost(Memblk *b);
extern void	dupdentries(void *p, int n);
extern ulong	embedattrsz(Memblk *f);
extern void	fatal(char *fmt, ...);
extern void	fsdump(int disktoo);
extern void	fsfmt(char *dev);
extern Memblk*	fsfreeze(void);
extern int	fsfull(void);
extern void	fslist(void);
extern int	fslowmem(void);
extern void	fsopen(char *dev);
extern void	fspolicy(void);
extern int	fsreclaim(void);
extern void	fssync(void);
extern void	gmeta(Fmeta *meta, void *buf, ulong nbuf);
extern Memblk*	hosttodisk(Memblk *b);
extern void	isdir(Memblk *f);
extern void	isfile(Memblk *f);
extern void	ismelted(Memblk *b);
extern void	isnotdir(Memblk *f);
extern void	isrwlocked(Memblk *f, int iswr);
extern void	listen9p(char *addr);
extern Memblk*	mballoc(u64int addr);
extern Memblk*	mbdup(Memblk *b);
extern int	mbfmt(Fmt *fmt);
extern Memblk*	mbget(u64int addr, int mkit);
extern Memblk*	mbhash(Memblk *b);
extern void	mbput(Memblk *b);
extern void	mbunhash(Memblk *b);
extern void	meltedref(Memblk *rb);
extern Mfile*	mfalloc(void);
extern Memblk*	mfchild(Memblk *f, int n);
extern void	mffree(Mfile *mf);
extern u64int	newblkaddr(void);
extern uvlong	now(void);
extern void	okaddr(u64int addr);
extern ulong	pmeta(void *buf, ulong nbuf, Fmeta *meta);
extern u64int	refaddr(u64int addr, int *idx);
extern void	rwlock(Memblk *f, int iswr);
extern void	rwunlock(Memblk *f, int iswr);
extern void	srv9p(char *srv);
extern char*	tname(int t);
extern long 	watime(Memblk *f, void *buf, long);
extern long 	wmtime(Memblk *f, void *buf, long);
extern long 	wname(Memblk *f, void *buf, long len);
