extern Path*	addelem(Path **pp, Memblk *f);
extern u64int	addrofref(u64int refaddr, int idx);
extern void	afree(Alloc *a, void *nd);
extern void*	anew(Alloc *a);
extern void	attach(Fid *fid, char *aname, char *uname);
extern void	changed(Memblk *b);
extern void	checktag(u64int tag, uint type, u64int addr);
extern void	clean(Memblk *b);
extern void	clearusers(void);
extern char*	cliworker9p(void *v, void**aux);
extern char*	cliworkerix(void *v, void**aux);
extern Fid*	clone(Cli *cli, Fid *fid, int no);
extern Path*	clonepath(Path *p);
extern void	consinit(void);
extern void	consprint(char *fmt, ...);
extern long	consread(char *buf, long count);
extern long	conswrite(char *ubuf, long count);
extern Memblk*	dballoc(uint type);
extern void	dbclear(u64int addr, int type);
extern u64int	dbdecref(u64int addr);
extern Memblk*	dbdup(Memblk *b);
extern Memblk*	dbget(uint type, u64int addr);
extern u64int	dbgetref(u64int addr);
extern u64int	dbincref(u64int addr);
extern long	dbread(Memblk *b);
extern void	dbsetref(u64int addr, int ref);
extern long	dbwrite(Memblk *b);
extern void	debug(void);
extern void	dfaccessok(Memblk *f, char *uid, int bits);
extern ulong	dfbno(Memblk *f, uvlong off, ulong *boffp);
extern void	dfcattr(Memblk *f, int op, char *name, void *val, long count);
extern u64int	dfchdentry(Memblk *d, u64int addr, u64int naddr, int iswr);
extern Memblk*	dfchild(Memblk *f, int n);
extern Memblk*	dfcreate(Memblk *parent, char *name, char *uid, ulong mode);
extern void	dfdropblks(Memblk *f, ulong bno, ulong bend);
extern int	dfdump(Memblk *f, int disktoo);
extern int	dffreeze(Memblk *f);
extern void	dflink(Memblk *d, Memblk *f);
extern void	dflist(Memblk *f, char *ppath);
extern int	dfmap(Memblk *f, Blkf pre, Blkf post, Blkf bf, int isdisk, int lk);
extern Path*	dfmelt(Path **pp, int nth);
extern ulong	dfpread(Memblk *f, void *a, ulong count, uvlong off);
extern ulong	dfpwrite(Memblk *f, void *a, ulong count, uvlong *off);
extern long	dfrattr(Memblk *f, char *name, void *val, long count);
extern int	dfreclaim(Memblk *f);
extern void	dfremove(Memblk *p, Memblk *f);
extern Blksl	dfslice(Memblk *f, ulong len, uvlong off, int iswr);
extern int	dfsync(Memblk *f);
extern void	dfunlink(Memblk *d, Memblk *f);
extern Memblk*	dfwalk(Memblk *d, char *name, int iswr);
extern long	dfwattr(Memblk *f, char *name, void *val, long nval);
extern void	disktohost(Memblk *b);
extern Path*	dropelem(Path **pp);
extern void	dupdentries(void *p, int n);
extern ulong	embedattrsz(Memblk *f);
extern void	fatal(char *fmt, ...);
extern void	fidclose(Fid *fid);
extern void	fidcreate(Fid *fid, char *name, int mode, ulong perm);
extern int	fidfmt(Fmt *fmt);
extern void	fidopen(Fid *fid, int mode);
extern long	fidread(Fid *fid, void *data, ulong count, vlong offset);
extern void	fidremove(Fid *fid);
extern long	fidwrite(Fid *fid, void *data, ulong count, uvlong *offset);
extern void	freerpc(Rpc *rpc);
extern void	fsdump(int disktoo);
extern void	fsfmt(char *dev);
extern Memblk*	fsfreeze(void);
extern int	fsfull(void);
extern void	fslist(void);
extern int	fslowmem(void);
extern uvlong	fsmemfree(void);
extern void	fsopen(char *dev);
extern void	fspolicy(void);
extern int	fsreclaim(void);
extern void	fsstats(void);
extern void	fssync(void);
extern Fid*	getfid(void* clino, int no);
extern void	gmeta(Fmeta *meta, void *buf, ulong nbuf);
extern Memblk*	hosttodisk(Memblk *b);
extern void	isdir(Memblk *f);
extern void	isfile(Memblk *f);
extern void	ismelted(Memblk *b);
extern void	isnotdir(Memblk *f);
extern int	isro(Memblk *f);
extern void	isrwlocked(Memblk *f, int iswr);
extern int	ixcallfmt(Fmt *fmt);
extern uint	ixpack(IXcall *f, uchar *ap, uint nap);
extern uint	ixpackedsize(IXcall *f);
extern void	ixstats(void);
extern uint	ixunpack(uchar *ap, uint nap, IXcall *f);
extern void	listen9pix(char *addr,  char* (*cliworker)(void *arg, void **aux));
extern Memblk*	mballoc(u64int addr);
extern Memblk*	mbdup(Memblk *b);
extern int	mbfmt(Fmt *fmt);
extern Memblk*	mbget(u64int addr, int mkit);
extern Memblk*	mbhash(Memblk *b);
extern void	mbput(Memblk *b);
extern void	mbunhash(Memblk *b);
extern void	meltedref(Memblk *rb);
extern int	member(char *uid, char *member);
extern Memblk*	mfchild(Memblk *f, int n);
extern u64int	newblkaddr(void);
extern Cli*	newcli(char *addr, int fd, int cfd);
extern Fid*	newfid(void* clino, int no);
extern Path*	newpath(Memblk *root);
extern Rpc*	newrpc(void);
extern void	ninestats(void);
extern void	nodebug(void);
extern uvlong	now(void);
extern void	okaddr(u64int addr);
extern void	ownpath(Path **pp);
extern void	parseusers(char *u);
extern ulong	pmeta(void *buf, ulong nbuf, Fmeta *meta);
extern void	putcli(Cli *cli);
extern void	putfid(Fid *fid);
extern void	putpath(Path *p);
extern u64int	refaddr(u64int addr, int *idx);
extern void	replied(Rpc *rpc);
extern int	rpcfmt(Fmt *fmt);
extern void	rwlock(Memblk *f, int iswr);
extern void	rwunlock(Memblk *f, int iswr);
extern void	srv9pix(char *srv, char* (*cliworker)(void *arg, void **aux));
extern char*	tname(int t);
extern void	walk(Fid *fid, char *wname);
extern long 	watime(Memblk *f, void *buf, long);
extern long 	wmtime(Memblk *f, void *buf, long);
extern long 	wname(Memblk *f, void *buf, long len);
