</$objtype/mkfile


TARG=\
	ix\
	ixget\
	ixc\
	nstest\
	catixd\

IXOFILES=\
	ch.$O\
	dbg.$O\
	mpool.$O\
	msg.$O\
	tses.$O\
	pack.$O\
	fmt.$O\

HFILES=\
	tses.h\
	msg.h\
	ch.h\
	dbg.h\
	mpool.h\
	conf.h\
	fs.h\
	file.h\
	ixreqs.h\
	cfile.h\

# not ready for installrm
BIN=.

</sys/src/cmd/mkmany

$O.ix: nsfile.$O fs.$O $IXOFILES
$O.ixget: ixreqs.$O $IXOFILES
$O.ixc: ixreqs.$O cfile.$O nsfile.$O $IXOFILES

$O.nstest: nstest.$O nsfile.$O dbg.$O $IXOFILES
	$LD $LDFLAGS -o $target $prereq


