</$objtype/mkfile

LIB=/$objtype/lib/liberror.a
OFILES=\
	echancreate.$O\
	emalloc.$O\

HFILES=/sys/include/error.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

</sys/src/cmd/mksyslib
