</$objtype/mkfile

MYLIBFILES=\
	file\
	patch\
	vacfs\

LIB=${MYLIBFILES:%=%.$O} /sys/src/cmd/venti/srv/libvs.a$O /sys/src/cmd/vac/pack.$O /sys/src/cmd/vac/error.$O

HFILES=\
	/sys/include/venti.h\
	stdinc.h\
	error.h\
	vac.h\
	dat.h\
	fns.h\

TARG=vtvacfs
BIN=/$objtype/bin

CFILES=${TARG:%=%.c} ${MYLIBFILES:%=%.c}

UPDATE=\
	mkfile\
	$CFILES\
	$HFILES\
	${TARG:%=/386/bin/%}

default:V: all

</sys/src/cmd/mkmany
